# Generated by Django 3.2.5 on 2021-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_episode_preview_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
