# Generated by Django 3.2.5 on 2021-08-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_episode_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
