# Generated by Django 3.2.5 on 2021-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_episode_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='buzz_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
