# Generated by Django 3.2.5 on 2021-08-20 21:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_episode_buzz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
